import localFont from "next/font/local";
import "./globals.css";
import { GoogleAnalytics, sendGAEvent } from "@next/third-parties/google";

import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   sendGAEvent("config", "G-F2LLSZHTYZ", {
  //     send_page_view: false,
  //   });
  // }, []);

  return (
    <html lang="en">
      <head>
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id="G-F2LLSZHTYZ"`}
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-F2LLSZHTYZ', {
                'send_page_view': false,
                'debug_mode':true
               
              });
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <GoogleAnalytics gaId="G-F2LLSZHTYZ" /> */}
        {children}
      </body>
    </html>
  );
}
